windows: custom artifact build using 7z

diff --git a/.github/workflows/build-idf-rust-dispatch.yaml b/.github/workflows/build-idf-rust-dispatch.yaml
--- a/.github/workflows/build-idf-rust-dispatch.yaml
+++ b/.github/workflows/build-idf-rust-dispatch.yaml
@@ -59,12 +59,12 @@ jobs:
         #os: [macos-latest, ubuntu-18.04 ]
         #os: [macos-latest, ubuntu-18.04, windows-latest]
         #os: [ubuntu-18.04]
-        #os: [windows-latest]
+        os: [windows-latest]
         # os: [macos-latest]
         # os: [ [self-hosted, Windows, X64] ]
         # os: [ [self-hosted, macOS, M1] ]
         #os: [ windows-self-hosted, macos-m1-self-hosted ]
-        os: [ windows-self-hosted ]
+        # os: [ windows-self-hosted ]
         include:
         # - os: macos-latest
         #   ARCH: ''
@@ -80,20 +80,20 @@ jobs:
         #   ASSET_NAME: 'rust-1.54.0-dev-x86_64-unknown-linux-gnu.tar.xz'
         #   ASSET_CONTENT_TYPE: 'application/x-tar'
         #   LLVM_ROOT_OPTION: ''
-        #- os: windows-latest
-        #  ARCH: ''
-        #  TARGET: win-x64
-        #  ASSET_PATH: 'build/dist/esp.zip'
-        #  ASSET_NAME: 'rust-1.54.0-dev-x86_64-pc-windows-msvc.zip'
-        #  ASSET_CONTENT_TYPE: 'application/zip'
-        #  LLVM_ROOT_OPTION: ''
-        - os: windows-self-hosted
-          ARCH: ''
-          TARGET: win-x64
-          ASSET_PATH: 'build/dist/esp.zip'
-          ASSET_NAME: 'rust-1.54.0-dev-x86_64-pc-windows-msvc.zip'
-          ASSET_CONTENT_TYPE: 'application/zip'
-          LLVM_ROOT_OPTION: '--llvm-root=C:/llvm-project'
+        - os: windows-latest
+         ARCH: ''
+         TARGET: win-x64
+         ASSET_PATH: 'build/dist/esp.zip'
+         ASSET_NAME: 'rust-1.54.0-dev-x86_64-pc-windows-msvc.zip'
+         ASSET_CONTENT_TYPE: 'application/zip'
+         LLVM_ROOT_OPTION: ''
+        # - os: windows-self-hosted
+        #   ARCH: ''
+        #   TARGET: win-x64
+        #   ASSET_PATH: 'build/dist/esp.zip'
+        #   ASSET_NAME: 'rust-1.54.0-dev-x86_64-pc-windows-msvc.zip'
+        #   ASSET_CONTENT_TYPE: 'application/zip'
+        #   LLVM_ROOT_OPTION: '--llvm-root=C:/llvm-project'
         # - os: macos-m1-self-hosted
         #   ARCH: ''
         #   TARGET: win-x64
@@ -121,34 +121,45 @@ jobs:
       #      wget --quiet https://github.com/georgik/idf-llvm-build/releases/download/v11.0.0/llvm-11.0.0-${{ matrix.TARGET }}.tar.xz
       #      tar xf llvm-11.0.0-${{ matrix.target }}.tar.xz
       - name: Prepare build
-        if: ${{ matrix.os == 'macos-m1-self-hosted' }}
         run: python3 src/bootstrap/configure.py ${{ matrix.LLVM_ROOT_OPTION }} --experimental-targets=Xtensa --enable-extended --tools=rustfmt --dist-compression-formats='xz'
         # run: python3 src/bootstrap/configure.py --llvm-root=llvm --experimental-targets=Xtensa --enable-extended --tools=rustfmt --dist-compression-formats='xz'
         # run: ./configure --experimental-targets=Xtensa --enable-extended --tools=rustfmt --dist-compression-formats='xz'
       - name: Build with x.py - only components
-        if: ${{ matrix.os == 'windows-latest' || matrix.os == 'windows-self-hosted' }}
+        if: ${{ matrix.os == 'windows-self-hosted' }}
         run: |
           python3 x.py build compiler/rustc src/tools/rustfmt library/std --stage 2
           python3 x.py dist src --stage 2
       - name: Build with x.py - dist packages
         if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' }}
         run: python3 x.py dist --stage 2 --exclude src/doc
+      - name: Build with x.py - dist packages - ignore failure
+        if: ${{ matrix.os == 'windows-latest' }}
+        run: python3 x.py dist --stage 2 --exclude src/doc || echo "Failure detected. Ignoring"
       - name: Build with x.py - dist packages - with cached LLVM
         if: ${{ matrix.os == 'macos-m1-self-hosted' }}
         run: python3 x.py dist --stage 2 --exclude src/doc --llvm-skip-rebuild TRUE
       - name: Dist bundle for Windows
-        if: ${{ matrix.os == 'windows-latest' || matrix.os == 'windows-self-hosted' }}
-        shell: bash
+        # Windows build has several issues:
+        # - long path problem in version 1.54.0, build of some dist artifacts fails
+        # - cp -r from stage2 is dangerous, because there is a src symlink to parent project dir which causes recursion
+        # Following code is workaround which assembles minimal distribution of toolchain which should be extracted to ~/.rustup/toolchains.
+        if: ${{ matrix.os == 'windows-self-hosted' || matrix.os == 'windows-latest' }}
+        shell: pwsh
         run: |
-          mkdir -p build/dist/esp
-          cp -r build/x86_64-pc-windows-msvc/stage2/* build/dist/esp
           cd build/dist
-          tar xf rust-src-1.54.0-dev.tar.xz
-          cp -r rust-src-1.54.0-dev/* build/dist/esp
-          cd esp
-          find . -name '*.pdb' -delete
-          cd ..
-          zip -r esp.zip esp
+          mkdir esp
+          pushd rust-1.54.0-dev-x86_64-pc-windows-msvc
+          cp -Recurse .\rustc\bin ..\esp\
+          cp -Recurse .\rustc\lib ..\esp\
+          cp -Recurse .\rustc\share ..\esp\
+          cp -ErrorAction SilentlyContinue -Recurse .\rust-std-x86_64-pc-windows-msvc\lib\* ..\esp\lib\
+          popd
+          7z e .\rust-src-1.54.0-dev.tar.xz
+          7z x .\rust-src-1.54.0-dev.tar
+          pushd rust-src-1.54.0-dev
+          cp -ErrorAction SilentlyContinue -Recurse .\rust-src\lib\* ..\esp\lib\
+          popd
+          7z a esp.zip esp/
       - name: Upload Release Asset
         id: upload-release-asset
         uses: actions/upload-release-asset@v1
